In [1]:
import cvxpy as cvx
import numpy as np

(CVXPY) Mar 27 09:12:18 AM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.9.3963). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) Mar 27 09:12:18 AM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.9.3963). Expected < 9.8.0. Please open a feature request on cvxpy to enable support for this version.')


## Rooks

In [67]:
n = 8 # board size
x_rook = cvx.Variable((n, n), boolean=True) # creating a variable for the board
obj = cvx.Maximize(cvx.sum(x_rook))
constraints = [(cvx.sum(x_rook, axis = 0) <= 1), #one rook in vertically
               (cvx.sum(x_rook, axis = 1) <= 1)] #one rook horizontally
prob = cvx.Problem(obj, constraints)

result = prob.solve()

print("Optimal number of rooks:", result)
x_rook.value

Optimal number of rooks: 8.0


array([[ 1.,  0.,  0., -0.,  0.,  0.,  0.,  0.],
       [ 0., -0.,  0.,  0.,  1.,  0.,  0., -0.],
       [-0.,  0.,  0.,  0.,  0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  0.,  0.,  0.,  1.],
       [ 0.,  0., -0.,  1.,  0.,  0.,  0.,  0.],
       [-0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0., -0.,  0.,  0.]])

## Bishops

In [61]:
n = 8  # board size
x_bishop = cvx.Variable((n, n), boolean=True)  # creating a variable for the board
obj = cvx.Maximize(cvx.sum(x_bishop))
constraints = []

#left to right diagonals
for l in range(x_bishop.shape[0]):
    diag = cvx.diag(x_bishop, k = l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]

for l in range(1,x_bishop.shape[0]):
    diag = cvx.diag(x_bishop, k = -l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]
    
# right to left diagonals
for l in range(x_bishop.shape[0]):
    diag = cvx.diag(x_bishop[::-1, :], k = l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]

for l in range(1,x_bishop.shape[0]):
    diag = cvx.diag(x_bishop[::-1, :], k = -l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]
    
prob = cvx.Problem(obj, constraints)
result = prob.solve()

print("Optimal number of bishops:", result)
x_bishop.value

Optimal number of bishops: 14.0


array([[ 1.,  1.,  1., -0.,  0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0., -0.],
       [ 1.,  0.,  0.,  0.,  0., -0.,  0.,  0.],
       [ 1.,  0., -0., -0., -0.,  1.,  1.,  0.]])

## Queens

In [13]:
n = 8 # board size
x_queen = cvx.Variable((n, n), boolean=True) # creating a variable for the board
obj = cvx.Maximize(cvx.sum(x_queen))
constraints = [(cvx.sum(x_queen, axis = 0) <= 1), #col
               (cvx.sum(x_queen, axis = 1) <= 1)] #row

#left to right diagonals
for l in range(x_queen.shape[0]):
    diag = cvx.diag(x_queen, k = l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]

for l in range(1,x_queen.shape[0]):
    diag = cvx.diag(x_queen, k = -l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]
    
# right to left diagonals
for l in range(x_queen.shape[0]):
    diag = cvx.diag(x_queen[::-1, :], k = l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]

for l in range(1,x_queen.shape[0]):
    diag = cvx.diag(x_queen[::-1, :], k = -l)
    diag_sum = cvx.sum(diag)
    constraints += [diag_sum <= 1]
                
prob = cvx.Problem(obj, constraints)

result = prob.solve()

print("Optimal number of queens:", np.round(result,decimals=10))
print(np.round(x_queen.value,decimals=10))

Optimal number of queens: 8.0
[[ 0. -0.  1.  0.  0.  0.  0. -0.]
 [-0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0. -0. -0.]
 [ 0. -0.  0.  0.  1.  0.  0.  0.]
 [ 0. -0.  0. -0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -0.  0. -0. -0.]]


## Kings

In [71]:
n = 8 # board size
x_king = cvx.Variable((n, n), boolean=True) # creating a variable for the board
obj = cvx.Maximize(cvx.sum(x_king))
constraints = []

# size of the submatrix
sub_rows, sub_cols = 2, 2

for i in range(n - sub_rows + 1):
    for j in range(n - sub_cols + 1):
        # extract submatrix
        submatrix = x_king[i:i+sub_rows, j:j+sub_cols]
        sum_submatrix = cvx.sum(submatrix)
        constraints += [sum_submatrix <= 1] # there can only be 1 king in the submatrix



prob = cvx.Problem(obj, constraints)

result = prob.solve()

print("Optimal number of kings:", result)
x_king.value

Optimal number of kings: 16.0


array([[1., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1.]])

## Knights

In [14]:
n = 8 # board size
x_knight = cvx.Variable((n, n), boolean=True) # creating a variable for the board
obj = cvx.Maximize(cvx.sum(x_knight))
constraints = []

for i in range(1, 8):
    for j in range(0,6):
        constraints += [(x_knight[i, j] + x_knight[i-1, j+2] <= 1)]
        
for i in range(0, 7):
    for j in range(0,6):
        constraints += [(x_knight[i, j] + x_knight[i+1, j+2] <= 1)]
        
for i in range(2, 8):
    for j in range(0,7):
        constraints += [(x_knight[i, j] + x_knight[i-2, j+1] <= 1)]
        
for i in range(0, 6):
    for j in range(0,7):
        constraints += [(x_knight[i, j] + x_knight[i+2, j+1] <= 1)]


prob = cvx.Problem(obj, constraints)

result = prob.solve()

print("Optimal number of Knights:", result)
x_knight.value

Optimal number of Knights: 32.0


array([[ 1., -0.,  1., -0.,  1., -0.,  1., -0.],
       [-0.,  1., -0.,  1., -0.,  1., -0.,  1.],
       [ 1., -0.,  1., -0.,  1., -0.,  1., -0.],
       [-0.,  1., -0.,  1., -0.,  1., -0.,  1.],
       [ 1., -0.,  1., -0.,  1., -0.,  1., -0.],
       [-0.,  1., -0.,  1., -0.,  1., -0.,  1.],
       [ 1., -0.,  1., -0.,  1., -0.,  1., -0.],
       [-0.,  1., -0.,  1., -0.,  1., -0.,  1.]])